### ISSUE TITLE
Can not run deploy command

### ISSUE THREAD

**Issue by yanhua365** [koistya/react-static-boilerplate#19]
I clone this repository,and can run `npm start`, but when I run 'npm run deploy' occurs errors: 

```
deploy
clean
pages
TypeError: Can't call method on  undefined
    at TypeError (native)
    at module.exports (/home/yanhua/work/demo/react-static-boilerplate/node_modules/babel-core/node_modules/core-js/modules/$.defined.js:3:63)
    at module.exports (/home/yanhua/work/demo/react-static-boilerplate/node_modules/babel-core/node_modules/core-js/modules/$.to-object.js:4:17)
    at Function.from (/home/yanhua/work/demo/react-static-boilerplate/node_modules/babel-core/node_modules/core-js/modules/es6.array.from.js:12:19)
    at _toConsumableArray (/home/yanhua/work/demo/react-static-boilerplate/tools/config.js:15:178)
    at Object.<anonymous> (/home/yanhua/work/demo/react-static-boilerplate/tools/config.js:89:8)
    at Module._compile (module.js:460:26)
    at normalLoader (/home/yanhua/work/demo/react-static-boilerplate/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/yanhua/work/demo/react-static-boilerplate/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)

```

I use Ubuntu and node0.12.4, Thanks.

--- [other tasks](https://waffle.io/koistya/react-static-boilerplate) ---

**Comment by koistya** [comment]
@yanhua365 Thanks for the report. Can you check please if this issue is still there?

**Comment by yanhua365** [comment]
Now error is:

```
[21:50:49] Starting 'render'...
Error: Invariant Violation: renderToString(): You must pass a valid ReactElement.
    at invariant (/home/yanhua/work/demo/react-static-boilerplate/node_modules/fbjs/lib/invariant.js:39:15)
    at Object.renderToString (/home/yanhua/work/demo/react-static-boilerplate/node_modules/react-dom/node_modules/react/lib/ReactServerRendering.js:31:83)
    at renderPage$ (/home/yanhua/work/demo/react-static-boilerplate/tools/render.js:40:20)

```

**Comment by koistya** [comment]
@yanhua365 check if you have react 0.14 installed in your local node_modules folder

**Comment by yanhua365** [comment]
@koistya It's OK. Thanks.
