### ISSUE TITLE
State changes fail on Chrome / Safari with "TypeError: Failed to execute 'replaceChild' on 'Node': parameter 1 is not of type 'Node'."

### ISSUE THREAD

**Issue by kmile** [koistya/react-static-boilerplate#59]
I'm trying to use a component that has an interactive element to it. This means that given a certain callback (in my case a Firebase value callback) the state of the component is updated.

In Chrome and Safari I get the following error:

```
Exception was thrown by user callback. TypeError: Failed to execute 'replaceChild' on 'Node': parameter 1 is not of type 'Node'.
    at TypeError (native)
    at Object.Danger.dangerouslyReplaceNodeWithMarkup (eval at <anonymous> (http://localhost:3000/app.js?1451773043685:2808:3), <anonymous>:140:25)
    at Object.ReactDOMIDOperations.dangerouslyReplaceNodeWithMarkupByID (eval at <anonymous> (http://localhost:3000/app.js?1451773043685:1239:3), <anonymous>:71:27)
    at Object.wrapper [as replaceNodeWithMarkupByID] (eval at <anonymous> (http://localhost:3000/app.js?1451773043685:717:3), <anonymous>:66:21)
    at ReactCompositeComponentMixin._replaceNodeWithMarkupByID (eval at <anonymous> (http://localhost:3000/app.js?1451773043685:2862:3), <anonymous>:579:31)
    at ReactCompositeComponentMixin._updateRenderedComponent (eval at <anonymous> (http://localhost:3000/app.js?1451773043685:2862:3), <anonymous>:571:12)
    at ReactCompositeComponentMixin._performComponentUpdate (eval at <anonymous> (http://localhost:3000/app.js?1451773043685:2862:3), <anonymous>:544:10)
    at ReactCompositeComponentMixin.updateComponent (eval at <anonymous> (http://localhost:3000/app.js?1451773043685:2862:3), <anonymous>:473:12)
    at wrapper [as updateComponent] (eval at <anonymous> (http://localhost:3000/app.js?1451773043685:717:3), <anonymous>:66:21)
    at ReactCompositeComponentMixin.performUpdateIfNecessary (eval at <anonymous> (http://localhost:3000/app.js?1451773043685:2862:3), <anonymous>:421:12) 
```
In Firefox everything works as expected. Am I doing something wrong here? It seems like the component is trying to update an HTML node that is no longer present in the DOM. I can see references to a similar error in the context of triggering `onBlur` on a node that gets removed, but I don't use `onBlur` or focussed elements in my code. Shouldn't React take care that an element is always valid? Or is that the `dangerous` part in `dangerouslyReplaceNodeWithMarkup` from the call stack?

I skip the Firebase callback for server side rendering, since it doesn't make sense to load real-time data from the database in the static site for this component. When I enable the callback, I get the following error during a `npm run build release`:

```
[23:47:48] Starting 'render'...
[23:47:50] Finished 'render' after 1371ms
[23:47:50] Finished 'build' after 16380ms
Warning: React can't find the root component node for data-reactid value `.27bre5ocr28.0.1`. If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time.
FIREBASE WARNING: Exception was thrown by user callback. TypeError: Cannot read property 'firstChild' of undefined
    at Object.ReactMount.findComponentRoot (/Users/kamielwanrooij/Projects/globulr/ui/node_modules/react/lib/ReactMount.js:715:39)
    at Object.ReactMount.findReactNodeByID (/Users/kamielwanrooij/Projects/globulr/ui/node_modules/react/lib/ReactMount.js:679:23)
    at Object.getNode (/Users/kamielwanrooij/Projects/globulr/ui/node_modules/react/lib/ReactMount.js:162:32)
    at Object.ReactDOMIDOperations.dangerouslyProcessChildrenUpdates (/Users/kamielwanrooij/Projects/globulr/ui/node_modules/react/lib/ReactDOMIDOperations.js:83:42)
    at Object.wrapper [as processChildrenUpdates] (/Users/kamielwanrooij/Projects/globulr/ui/node_modules/react/lib/ReactPerf.js:66:21)
    at processQueue (/Users/kamielwanrooij/Projects/globulr/ui/node_modules/react/lib/ReactMultiChild.js:160:31)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/Users/kamielwanrooij/Projects/globulr/ui/node_modules/react/lib/ReactMultiChild.js:334:13)
    at ReactDOMComponent.Mixin._updateDOMChildren (/Users/kamielwanrooij/Projects/globulr/ui/node_modules/react/lib/ReactDOMComponent.js:871:12)
    at ReactDOMComponent.Mixin.updateComponent (/Users/kamielwanrooij/Projects/globulr/ui/node_modules/react/lib/ReactDOMComponent.js:700:10)
    at ReactDOMComponent.Mixin.receiveComponent (/Users/kamielwanrooij/Projects/globulr/ui/node_modules/react/lib/ReactDOMComponent.js:645:10)
/Users/kamielwanrooij/Projects/globulr/ui/node_modules/firebase/lib/firebase-node.js:43
ion(){N("Exception was thrown by user callback.",b.stack||"");throw b;},Math.f
                                                                    ^
TypeError: Cannot read property 'firstChild' of undefined
    at Object.ReactMount.findComponentRoot (/Users/kamielwanrooij/Projects/globulr/ui/node_modules/react/lib/ReactMount.js:715:39)
    at Object.ReactMount.findReactNodeByID (/Users/kamielwanrooij/Projects/globulr/ui/node_modules/react/lib/ReactMount.js:679:23)
    at Object.getNode (/Users/kamielwanrooij/Projects/globulr/ui/node_modules/react/lib/ReactMount.js:162:32)
    at Object.ReactDOMIDOperations.dangerouslyProcessChildrenUpdates (/Users/kamielwanrooij/Projects/globulr/ui/node_modules/react/lib/ReactDOMIDOperations.js:83:42)
    at Object.wrapper [as processChildrenUpdates] (/Users/kamielwanrooij/Projects/globulr/ui/node_modules/react/lib/ReactPerf.js:66:21)
    at processQueue (/Users/kamielwanrooij/Projects/globulr/ui/node_modules/react/lib/ReactMultiChild.js:160:31)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/Users/kamielwanrooij/Projects/globulr/ui/node_modules/react/lib/ReactMultiChild.js:334:13)
    at ReactDOMComponent.Mixin._updateDOMChildren (/Users/kamielwanrooij/Projects/globulr/ui/node_modules/react/lib/ReactDOMComponent.js:871:12)
    at ReactDOMComponent.Mixin.updateComponent (/Users/kamielwanrooij/Projects/globulr/ui/node_modules/react/lib/ReactDOMComponent.js:700:10)
    at ReactDOMComponent.Mixin.receiveComponent (/Users/kamielwanrooij/Projects/globulr/ui/node_modules/react/lib/ReactDOMComponent.js:645:10)
```

Which might be related...?

**Comment by kmile** [comment]
Issue fixed by using `componentDidMount`: http://stackoverflow.com/questions/34592233/react-cant-replace-server-side-rendered-node-in-browser-callback
