### ISSUE TITLE
How do I create webpack import aliases in this boilerplate ?

### ISSUE THREAD

**Issue by pierrecholhot** [koistya/react-static-boilerplate#86]
I am trying to `import` components this way:

```
import PageHeader from 'components/PageHeader';
import FormHelper from 'core/helpers/FormHelper';
```

rather than having to count the number of subdirs as follow:

```
import PageHeader from '../../../../components/PageHeader';
import FormHelper from '../../../../core/helpers/FormHelper';
```

-----

So I've added the usual `resolve` key to the `weback.config.js` as follows:

```
config.resolve = {
  root: [
    path.resolve('./')
  ]
};
```

It "seems" like working (no webpack errors), **however the build breaks when trying to start the app**.

```
Error: Cannot find module 'components/PageHeader'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/build/app.node.js:7505:20)
    at __webpack_require__ (/build/app.node.js:21:30)
    at Object.module.exports.Object.defineProperty.value (/build/app.node.js:5939:31)
    at __webpack_require__ (/build/app.node.js:21:30)
    at HomepageInit (/build/app.node.js:158:14)
    at Object.route$ (/build/app.node.js:170:43)
```

I am assuming that this error is triggered by `node.app.js` where I can see that my components are in the same "level" as the `node_modules`...

```
/* 126 */
/***/ function(module, exports) {
  module.exports = require("babel-runtime/helpers/slicedToArray");
/***/ },
/* 127 */
/***/ function(module, exports) {
  module.exports = require("components/Navigation"); // <-----------------
/***/ },
/* 128 */
/***/ function(module, exports) {
  module.exports = require("components/PageHeader"); // <-----------------
/***/ },
/* 129 */
/***/ function(module, exports) {
  module.exports = require("components/Panel"); // <-----------------
/***/ },
/* 130 */
/***/ function(module, exports) {
  module.exports = require("deep-equal");
/***/ },
/* 131 */
/***/ function(module, exports) {
  module.exports = require("diacritics");
```

I've tried overriding the `config.resolve` for the PageRendering (with different values) but nothing changed.

What can I do to make it work ?

**Comment by pierrecholhot** [comment]
I've found a solution, very close to what I wanted to achieve, however I had to prepend a `~` to the alias so it doesn't get treated as a node module:

```
config.resolve = {
  alias: {
    "~components": path.resolve(__dirname, '../components'),
    "~decorators": path.resolve(__dirname, '../core/scripts/decorators'),
    "~helpers": path.resolve(__dirname, '../core/scripts/helpers'),
    "~i18n": path.resolve(__dirname, '../core/i18n'),
  }
};
```

usage:
```
import fetch from '~helpers/fetch';
import header from '~components/header';
```

**Comment by ImanMh** [comment]
Why web-pack doesn't understand this without `~`?
