### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined error on node tools/deploy.gh --release

### ISSUE THREAD

**Issue by amite** [koistya/react-static-boilerplate#93]
```
ReferenceError: regeneratorRuntime is not defined
    at Function.open (/Users/amiterandole/Documents/current/webdev/static-react/node_modules/git-repository/lib/Repository.js:198:14)
    at Promise (/Users/amiterandole/Documents/current/webdev/static-react/tools/deploy.gh.js:27:19)
    at module.exports.task (/Users/amiterandole/Documents/current/webdev/static-react/tools/deploy.gh.js:24:39)
    at task (/Users/amiterandole/Documents/current/webdev/static-react/tools/task.js:18:55)
    at Object.<anonymous> (/Users/amiterandole/Documents/current/webdev/static-react/tools/deploy.gh.js:24:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

I am running node -v6.2.0

**Comment by v3yr0n** [comment]
Clean install? Have you run npm install?

**Comment by amite** [comment]
Yes!

**Comment by dreamershl** [comment]
same here

**Comment by dreamershl** [comment]
find the solution. after add this "require('babel-polyfill');" into the deploy.gh.js. the issue is solved. According to here "https://phabricator.babeljs.io/T6676", seems it is caused by the stict mode.
