### ISSUE TITLE
`$ npm run deploy` not working

### ISSUE THREAD

**Issue by mnishiguchi** [koistya/react-static-boilerplate#94]
I followed the instruction and it worked perfectly up to `$ npm start`; however, I keep on getting the following error messages when I run `$ npm run deploy`. I tried to figure out but it was beyond me. If anyone can give me advice, that would be great.

```
$ npm run deploy

> @ deploy /Users/masa/projects/react/react_trivia_2
> node tools/deploy.gh --release

[21:44:38] Starting 'deploy'...
ReferenceError: regeneratorRuntime is not defined
    at Function.open (/Users/masa/projects/react/react_trivia_2/node_modules/git-repository/lib/Repository.js:198:14)
    at Promise (/Users/masa/projects/react/react_trivia_2/tools/deploy.gh.js:26:19)
    at module.exports.task (/Users/masa/projects/react/react_trivia_2/tools/deploy.gh.js:23:39)
    at task (/Users/masa/projects/react/react_trivia_2/tools/task.js:18:55)
    at Object.<anonymous> (/Users/masa/projects/react/react_trivia_2/tools/deploy.gh.js:23:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
```

**Comment by reecefenwick** [comment]
I encountered this issue as well.

Look to issue #93 for the solution.

Add require('babel-polyfill'); into your deploy script.

**Comment by mnishiguchi** [comment]
@reecefenwick Thank you for your advice! It worked.
